# Generated by Django 6.0.1 on 2026-01-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_perfil_foto_alter_perfil_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
