# Generated by Django 6.0.1 on 2026-01-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='pasos',
            new_name='ingredientes',
        ),
        migrations.AddField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.categoria'),
        ),
    ]
