# Generated by Django 6.0.1 on 2026-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_rename_pasos_receta_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(),
        ),
    ]
