# Generated by Django 6.0.1 on 2026-01-17 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_alter_receta_imagen_alter_receta_instrucciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='instrucciones',
            new_name='pasos',
        ),
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.categoria'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
