# Generated by Django 6.0.1 on 2026-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_rename_instrucciones_receta_pasos_receta_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
